"""datetimeNotOpt

Revision ID: 2a88d4985416
Revises: 90e96399bd00
Create Date: 2022-07-26 18:26:58.948600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a88d4985416'
down_revision = '90e96399bd00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
