"""ExecutorRelation2

Revision ID: 90e96399bd00
Revises: 991bc24f62c5
Create Date: 2022-07-25 21:21:46.522649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e96399bd00'
down_revision = '991bc24f62c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
