"""ExecutorRelation

Revision ID: 991bc24f62c5
Revises: bb29b5c5ecb1
Create Date: 2022-07-25 20:38:05.846076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991bc24f62c5'
down_revision = 'bb29b5c5ecb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
