"""IsExecuteFieldTask

Revision ID: f6919b6bfb91
Revises: 2a88d4985416
Create Date: 2022-07-29 15:06:23.325801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6919b6bfb91'
down_revision = '2a88d4985416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_execute', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_execute')
    # ### end Alembic commands ###
